title = "CDK로 멀티 리전 EKS 클러스터 풀스택 배포"
googleAnalytics = "UA-165390845-2"
anguageCode = "ko-KR"
defaultContentLanguage = "ko"
theme = "hugo-theme-learn"
showHeaderLanguageChooser=true
defaultContentLanguageInSubdir= true


[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  showVisitedLinks = false
  disableBreadcrumb = false
  disableNextPrev = false
  themeVariant = "aws"
  disableInlineCopyToClipBoard = false
  author = "Jiwon Yeom"

[[menu.shortcuts]] 
  name = "<i class='fab fa-aws'></i> CDK workshop"
  url = "https://cdkworkshop.com/"
  weight = 1000
[[menu.shortcuts]] 
  name = "<i class='fab fa-aws'></i> CDK Roadmap"
  url = "https://github.com/orgs/aws/projects/7"
  weight = 1010

[[menu.shortcuts]]
  name = "<i class='fab fa-github'></i> Github for entire code"
  url = "https://github.com/yjw113080/aws-cdk-eks-multi-region"
  weight = 1020

[[menu.shortcuts]]
  name = "<i class='far fa-envelope'></i> feedback"
  url = "https://github.com/yjw113080/aws-cdk-eks-multi-region-workshop/issues/new"
  weight = 1030



[Languages]
  [Languages.ko]
    weight = 1
    languageName = "한국어"

  [Languages.en]
    weight = 2
    languageName = "English"
    title = "Full-stack deployment of Multi-Region EKS cluster with CDK"

[deployment]
  [[deployment.targets]]
    name = "s3"
    URL = "s3://demogo-multiregion-eks?region=ap-northeast-2"
